Cloning the NYT web page
raovikrant82/NYTMicroverseProject pull request #1
Opened 2020-10-22 16:46 UTC by raovikrant82

First project at Microverse using HTML and CSS to clone NYTimes web page. Mainly we used Grid, Float and Flex to replicate the page.

2020-10-22 18:40 UTC, rammazzoti2000 requested changes
### Hello @raovikrant82  and @akshay-narkar  :wave: well done on this project
The project is well built, most of the HTML code is semantic, commits are short and meaningful. Good job on `Editor's picks` using `<aside>` tag :smile: and also using flexbox with a combination of all three techniques (float, flex, grid)

As you would expect there are a few issues to fix before approving the project, but nothing major, please follow the comments bellow :point_down: 

### :stop_sign: Required Changes :construction: :construction_worker:
- [x] The [Webhint linters](https://github.com/raovikrant82/NYTMicroverseProject/pull/1/checks?check_run_id=1293816666) for your HTML didn't pass the checking, make sure to fix all the errors.
- [x] The README.md file should be a bit more descriptive, add a screenshot. Take a look at mine to have a clearer idea on how it should be :point_right: [link here](https://github.com/rammazzoti2000/Positioning-and-Floating-Elements/blob/master/README.md)
- [x] Please refactor your CSS code a little bit regarding repeating properties, which is considered a bad practice. My suggestion is that you create classes for specific properties and apply them to the elements you want.
- [x] The navbar should have a fixed position (it sticks to the top part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)), make sure, after that, to add `z-index: 999` and `width: 100%` to avoid rendering issues, more details in the inline comments bellow :point_down: .
- [x] The main picture should be semantic meaning the it should use semantic HTML elements like `<figure>` for the picture and `<figcaption>`  for its description, more details in the inline comments bellow :point_down: .
- [x] Make sure the `central-section-article` container to change it from a `<div>` element to a `<section>` element to improve the HTML semantic of your code
## Optional:
To improve even more you HTML semantic you could wrap your main content inside a `<main>` tag this would semantically specify the main content from the rest of the page.
The `<main>` element behaves like a main landmark role. Landmarks can be used by assistive technology to quickly identify and navigate to large sections of the document. 

### <em>Kindly fix the REQUIRED issues and send for another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of ```@ale[x360]``` if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-10-22 18:40 UTC, rammazzoti2000 commented on index.html
> +    </section>
Here the picture has a description, this means that that picture could be a `<figure>` element and in addition to that could be added a `<figcaption>` as description, this will greatly improve the HTML semantic of your code, please look over the [w3schols](https://www.w3schools.com/tags/tag_figcaption.asp) for a complete explanation.

2020-10-22 18:40 UTC, rammazzoti2000 commented on index.html
> +    <div class="center-section-article">
change ` <div class="center-section-article">` to ` <section class="center-section-article">` to improve HTML semantic

2020-10-22 18:40 UTC, rammazzoti2000 commented on index.html
> +<div class="center-section-article">
change ` <div class="center-section-article">` to ` <section class="center-section-article">` to improve HTML semantic

2020-10-22 18:40 UTC, rammazzoti2000 commented on index.html
> + <div class="center-section-article">
change ` <div class="center-section-article">` to ` <section class="center-section-article">` to improve HTML semantic

2020-10-23 16:40 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @raovikrant82 and @akshay-narkar  :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-10-23 16:41 UTC, merged